### ISSUE TITLE
generate views content for navbar

### ISSUE THREAD

**Issue by Eschults** [jchantereau/tartine#10]
- set navigational links (user `if user_signed_in?` to display `users/show` link and photo)

**Comment by jchantereau** [comment]
@Eschults client wants the search bar to be integrated in the navbar on the index page
Design: page 6 of the "Cahier des charges à valider" : https://drive.google.com/drive/folders/0B2aFscgf2rwXa0RfRmk5UUlxc3M

**Comment by Eschults** [comment]
@jchantereau c'est un peu redondant avec le form déjà existant dans la vue index, s'ils veulent cette navbar pour d'autres pages je veux bien, mais juste pour celle-là je sens que je vais la coder pour rien ils vont vouloir l'enlever à mon avis
