### ISSUE TITLE
Logo display in welcome mail

### ISSUE THREAD

**Issue by Eschults** [jchantereau/tartine#106]
Tu mets en dur `width: 400px; height: 100px;` du coup l'image est étirée, en général faut mettre une contrainte que sur la width ou que sur la height et utiliser une option de cloudinary genre `scale: fit` ou des trucs comme ça

**Comment by jchantereau** [comment]
Yes j'ai changé ca mais je n'arrive pas à voir le résultat, sur le mail d'inscription c'est encore l'ancien qui apparait alors que je l'ai changé sur Cloudinary
