### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by jchantereau** [jchantereau/tartine#121]
Create redirection between monbeauterroir.com to https://www.monbeauterroir.com

**Comment by Eschults** [comment]
c'est déjà le cas non ?

**Comment by jchantereau** [comment]
nop tu dois avoir une redirection automatique vu ton historique

<img width="1280" alt="screen shot 2016-08-04 at 3 47 19 pm" src="https://cloud.githubusercontent.com/assets/14294030/17404085/d2541504-5a5a-11e6-9bad-cdaef848980f.png">

**Comment by jchantereau** [comment]
On peut voir ca demain comme ca tu me montres comment gérer ce genre d'issue

**Comment by Eschults** [comment]
yes, c'est fait c'est un réglage au niveau du gestionnaire de DNS, je te montrerai je viens de le faire sur cloudflare, chez moi c bon

**Comment by jchantereau** [comment]
Top !
