### ISSUE TITLE
Map - Some more feedbacks

### ISSUE THREAD

**Issue by jchantereau** [jchantereau/tartine#37]
@Eschults https://trello.com/c/yJ6CAL12/21-category-page

**Comment by jchantereau** [comment]
+ points 23 à 25 de : https://trello.com/c/7DXTDsQw/20-homepage
@Eschults

**Comment by Eschults** [comment]
@jchantereau le délire du je déplace la map ça refresh la search (point 7) ya un peu de taf, ça m'étonne que ce soit prévu dans leur MVP tu me confirmeras je le laisse de côté en attendant
