### ISSUE TITLE
Limit number of characters for visit desc on booking page

### ISSUE THREAD

**Issue by jchantereau** [jchantereau/tartine#71]
For instance: https://mon-beau-terroir.herokuapp.com/visits/21/bookings/new

**Comment by Eschults** [comment]
A combien de caractères ? La création de visite est faite par le producer ou par l'admin ?

**Comment by jchantereau** [comment]
Il faut test sur les différents device, mais je dirais 450 espaces compris
C'est l'admin

**Comment by Eschults** [comment]
ok on va juste ajouter une validation en back c'est vite fait ;)

**Comment by jchantereau** [comment]
C'est pas limiter le texte en back mais en front, c'est le meme texte que sur la page d'avant qu'il faut conserver dans son intégralité
là c'est juste en front pour avoir un affichage agréable

**Comment by Eschults** [comment]
Ok je vois, dans ce cas qu'est-ce que tu penses de regrouper le `h3` et le `p` dans une `div#limited-description` et du lui mettre une `height` fixe en pixels et un `overflow: scroll;` ?

**Comment by Eschults** [comment]
OK, semaine pro jsuis dispo jeudi!

**Comment by jchantereau** [comment]
Ok. Je serai en corse mais si tu peux avancer sur le paiement c'est cool ;)
On Mon, 27 Jun 2016 at 16:41, Edward Schults <notifications@github.com>
wrote:

> OK, semaine pro jsuis dispo jeudi!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jchantereau/tartine/issues/71#issuecomment-228765827>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANocDhgxU-yHDzizeFuKltoS6XQNvISbks5qP-EKgaJpZM4I_HII>
> .
>
-- 
Julien Chantereau
06.60.33.30.84

**Comment by Eschults** [comment]
ça roule 👍

**Comment by jchantereau** [comment]
@Eschults Ils ne sont plus sûr de garder le texte ici -> Let's wait
