### ISSUE TITLE
Emails - booking update - differentiate validate/modify/cancel

### ISSUE THREAD

**Issue by jchantereau** [jchantereau/tartine#82]
How can I highlight if it's a validation, modification requirement or cancellation ?

**Comment by Eschults** [comment]
@jchantereau tu peux le faire directement dans le controller, `if else` sur le status et t'as un template pour `accepted` un template pour les modif / annul

**Comment by Eschults** [comment]
d'ailleurs on avait dit que l'agri quand il valide ça fait passer le statut à `accepted` mais c'est l'admin qui fait passer le champ `:accepted` à true non ? pcq là pour l'instant l'agri valide et ça valide direct, donc ça génère le paiement du client

**Comment by jchantereau** [comment]
@Eschults Si l'agri valide une demande de réservation, normalement on peut balancer le paiement. L'admin n'intervient que pour les demandes de modification ou annulation. Je double check avec eux

**Comment by jchantereau** [comment]
@Eschults "Quand l'agri valide (via son espace sur le site), cela enclenche la procédure de paiement (la carte est débitée, et l'argent stocké sur le ewallet). L'argent est versé au producteur uniquement après la visite (quand on valide sur mangopay que la visite a bien eu lieu)"
