### ISSUE TITLE
Multi categories management

### ISSUE THREAD

**Issue by jchantereau** [jchantereau/tartine#87]
@Eschults Lorsqu'on a plusieurs produits, cela affiche autant de picto sur la carte que de produits. On pourrait décider d'en afficher un seul mais comment gérer le cas où une ferme à plusieurs produits de plusieurs catégories et qu'on filtre le résultat ?

Ex : Une ferme à des produits des catégories vin et fromage, on affiche le picto du vin sur la carte mais on filtre par fromage ensuite

**Comment by Eschults** [comment]
ok done ;) will be in next PR
