### ISSUE TITLE
[pre-prod] Delete farm

### ISSUE THREAD

**Issue by jchantereau** [jchantereau/tartine#89]
@Eschults I can't delete the 2 remaining fake farms on preprod (Ferme de loze + julie).
There are no products, booking, visit or anything linked to those farms

**Comment by Eschults** [comment]
what's the error message?

**Comment by jchantereau** [comment]
@Eschults I don't have it, it's on heroku + I can't find it in the logs

**Comment by Eschults** [comment]
try to delete it from `heroku run rails c`, you'll get the logs then
